name: Show generated diff

on:
  pull_request:

permissions:
  contents: read

jobs:
  diff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Generate plugin manifest
        run: go generate ./plugins
      - name: Print generated diff
        run: git --no-pager diff -- plugins/manifest_gen.go
